In [2]:
import numpy as np

# Sum

In [12]:
As = np.array([[1, 2, 3], [3, 2, 1]])
Bs = np.array([[0, 0, 0], [0, 0, 0]])
Cs = A + B
Cs

array([[1, 2, 3],
       [3, 2, 1]])

# Multiplication

In [13]:
A = np.array([[1, 2, 3], [3, 2, 1]])
B = np.array([[0, 2], [1, -1], [0, 1]])
print(f'M1: {A}\n')
print(f'M2: {B}')

M1: [[1 2 3]
 [3 2 1]]

M2: [[ 0  2]
 [ 1 -1]
 [ 0  1]]


In [14]:
C = np.dot(A, B)
C

array([[2, 3],
       [2, 5]])